version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: UserPostgres
    restart: always
    environment:
      POSTGRES_DB: myDatabase
      POSTGRES_USER: myUsername
      POSTGRES_PASSWORD: myPassword
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5100:5432"
    volumes:
      - ./initDatabase/user:/docker-entrypoint-initdb.d
    networks:
      - user-network
  # Serviço do Spring Boot (userservice)
  userservice:
    image: wiliian/user-service:v2
    build:
      context: ../userService/
      dockerfile: ../userService/Dockerfile
    # volumes:
    #   - .{PWD}/../userService/  # Sincroniza os arquivos locais com o container
    container_name: userService
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myDatabase
      SPRING_DATASOURCE_USERNAME: myUsername
      SPRING_DATASOURCE_PASSWORD: myPassword
    networks:
      - user-network

volumes:
  pgdata:

networks :
  user-network :
    driver : bridge
